### ISSUE TITLE
Error messages for required form fields left blank

### ISSUE THREAD

**Issue by cjaiello** [cjaiello/Slack-Standup-Report-Bot#7]
When user leaves required fields black and hits "submit," the screen should tell them what they didn't fill in that was required.

StandupSignupForm (see app.py) is the form class, and anything marked "validators=[validators.required()]" is a required piece.

**Comment by Rud156** [comment]
I would like to take a look into this. Will be submitting a PR.

**Comment by chetanya-shrimali** [comment]
Hey @cjaiello i would like to work on this issue!!
